export const FUNNEL_STATES = {
  VISITOR: 'FUNNEL_VISITOR',
  DEEP_LINK_MEMBER_ENTRY: 'FUNNEL_DEEP_LINK_MEMBER_ENTRY',
  MEMBER_PAGE: 'FUNNEL_MEMBER_PAGE',
  JOIN_CTA: 'FUNNEL_JOIN_CTA',
  RECRUITMENT_DEEP_LINK_ENTRY: 'FUNNEL_RECRUITMENT_DEEP_LINK_ENTRY',
  RECRUITMENT_FORM: 'FUNNEL_RECRUITMENT_FORM',
  RECRUITMENT_CLOSED: 'FUNNEL_RECRUITMENT_CLOSED',
  SUBMISSION_ERROR: 'FUNNEL_SUBMISSION_ERROR',
  SUBMISSION_SUCCESS: 'FUNNEL_SUBMISSION_SUCCESS',
  ADMIN_INBOX: 'FUNNEL_ADMIN_INBOX',
  MEMBER_NOT_FOUND: 'FUNNEL_MEMBER_NOT_FOUND',
} as const;

export type FunnelState = (typeof FUNNEL_STATES)[keyof typeof FUNNEL_STATES];

export type FunnelTransition = {
  from: FunnelState;
  to: FunnelState;
  event: string;
};

export const FUNNEL_TRANSITIONS: readonly FunnelTransition[] = [
  { from: FUNNEL_STATES.VISITOR, to: FUNNEL_STATES.MEMBER_PAGE, event: 'SELECT_PUBLIC_MEMBER' },
  { from: FUNNEL_STATES.VISITOR, to: FUNNEL_STATES.DEEP_LINK_MEMBER_ENTRY, event: 'OPEN_MEMBER_DEEP_LINK' },
  { from: FUNNEL_STATES.DEEP_LINK_MEMBER_ENTRY, to: FUNNEL_STATES.MEMBER_PAGE, event: 'PUBLIC_MEMBER_EXISTS' },
  { from: FUNNEL_STATES.DEEP_LINK_MEMBER_ENTRY, to: FUNNEL_STATES.MEMBER_NOT_FOUND, event: 'PUBLIC_MEMBER_UNAVAILABLE' },
  { from: FUNNEL_STATES.MEMBER_PAGE, to: FUNNEL_STATES.JOIN_CTA, event: 'SELECT_JOIN_CTA_WHILE_OPEN' },
  { from: FUNNEL_STATES.JOIN_CTA, to: FUNNEL_STATES.RECRUITMENT_FORM, event: 'OPEN_RECRUITMENT_ROUTE' },
  { from: FUNNEL_STATES.VISITOR, to: FUNNEL_STATES.RECRUITMENT_DEEP_LINK_ENTRY, event: 'OPEN_RECRUITMENT_DEEP_LINK' },
  { from: FUNNEL_STATES.RECRUITMENT_DEEP_LINK_ENTRY, to: FUNNEL_STATES.RECRUITMENT_FORM, event: 'RECRUITMENT_CYCLE_OPEN' },
  { from: FUNNEL_STATES.RECRUITMENT_DEEP_LINK_ENTRY, to: FUNNEL_STATES.RECRUITMENT_CLOSED, event: 'RECRUITMENT_CYCLE_CLOSED' },
  { from: FUNNEL_STATES.RECRUITMENT_FORM, to: FUNNEL_STATES.SUBMISSION_SUCCESS, event: 'SUBMISSION_PERSISTED' },
  { from: FUNNEL_STATES.RECRUITMENT_FORM, to: FUNNEL_STATES.SUBMISSION_ERROR, event: 'SUBMISSION_FAILED' },
  { from: FUNNEL_STATES.SUBMISSION_ERROR, to: FUNNEL_STATES.RECRUITMENT_FORM, event: 'RETRY_SUBMISSION' },
  { from: FUNNEL_STATES.SUBMISSION_SUCCESS, to: FUNNEL_STATES.ADMIN_INBOX, event: 'APPLICATION_AVAILABLE_TO_ADMIN' },
  { from: FUNNEL_STATES.RECRUITMENT_CLOSED, to: FUNNEL_STATES.RECRUITMENT_FORM, event: 'NEW_OPEN_CYCLE_AVAILABLE' },
] as const;

export function canTransition(from: FunnelState, to: FunnelState): boolean {
  return FUNNEL_TRANSITIONS.some((transition) => transition.from === from && transition.to === to);
}
